import type { FC } from 'react';
import styled from 'styled-components';
import { PublicNavbar } from '../components/PublicNavbar';
import { Footer } from '../components/Footer';

const Page = styled.main`
	min-height: 100vh;
	background: linear-gradient(180deg, #0b1220 0%, #0f172a 100%);
	color: #ffffff;
	display: flex;
	flex-direction: column;
`;

const Container = styled.div`
	max-width: 800px;
	margin: 0 auto;
	padding: 2rem 1rem 3rem 1rem;
`;

const Heading = styled.h1`
	margin: 0 0 1.5rem 0;
	font-size: clamp(1.8rem, 4vw, 2.2rem);
	font-weight: 800;
	text-align: center;
`;

const Section = styled.section`
	margin-bottom: 2rem;
`;

const SectionTitle = styled.h2`
	margin: 0 0 1rem 0;
	font-size: 1.4rem;
	font-weight: 700;
	color: #c7d2fe;
`;

const SubSectionTitle = styled.h3`
	margin: 1.5rem 0 0.75rem 0;
	font-size: 1.2rem;
	font-weight: 600;
	color: #a5b4fc;
`;

const Paragraph = styled.p`
	margin: 0 0 1rem 0;
	color: #cbd5e1;
	line-height: 1.6;
`;

const List = styled.ul`
	color: #cbd5e1;
	line-height: 1.6;
	margin: 0 0 1rem 1.5rem;
`;

const ListItem = styled.li`
	margin-bottom: 0.5rem;
`;

const LastUpdated = styled.p`
	color: #94a3b8;
	font-style: italic;
	text-align: center;
	margin-top: 2rem;
`;

export const PrivacyPolicy: FC = () => {
	return (
		<Page>
			<PublicNavbar />
			<Container>
				<Heading>Privacy Policy</Heading>
				
				<Section>
					<Paragraph>
						Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
					</Paragraph>
					
					<Paragraph>
						This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
					</Paragraph>
					
					<Paragraph>
						We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
					</Paragraph>
				</Section>
				
				<Section>
					<SectionTitle>Interpretation and Definitions</SectionTitle>
					
					<SubSectionTitle>Interpretation</SubSectionTitle>
					<Paragraph>
						The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
					</Paragraph>
					
					<SubSectionTitle>Definitions</SubSectionTitle>
					<List>
						<ListItem><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</ListItem>
						<ListItem><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</ListItem>
						<ListItem><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to HirePath.</ListItem>
						<ListItem><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</ListItem>
						<ListItem><strong>Country</strong> refers to: Norway</ListItem>
						<ListItem><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</ListItem>
						<ListItem><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</ListItem>
						<ListItem><strong>Service</strong> refers to the Website.</ListItem>
						<ListItem><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</ListItem>
						<ListItem><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</ListItem>
						<ListItem><strong>Website</strong> refers to HirePath, accessible from <a href="https://hirepath.example.com" style={{color: '#818cf8'}}>https://hirepath.example.com</a></ListItem>
						<ListItem><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</ListItem>
					</List>
				</Section>
				
				<Section>
					<SectionTitle>Collecting and Using Your Personal Data</SectionTitle>
					
					<SubSectionTitle>Types of Data Collected</SubSectionTitle>
					
					<Paragraph><strong>Personal Data</strong></Paragraph>
					<Paragraph>
						While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
					</Paragraph>
					<List>
						<ListItem>Email address</ListItem>
						<ListItem>First name and last name</ListItem>
						<ListItem>Phone number</ListItem>
						<ListItem>Usage Data</ListItem>
					</List>
					
					<Paragraph><strong>Usage Data</strong></Paragraph>
					<Paragraph>
						Usage Data is collected automatically when using the Service.
					</Paragraph>
					<Paragraph>
						Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
					</Paragraph>
					<Paragraph>
						When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
					</Paragraph>
					<Paragraph>
						We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
					</Paragraph>
					
					<Paragraph><strong>Information from Third-Party Social Media Services</strong></Paragraph>
					<Paragraph>
						The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:
					</Paragraph>
					<List>
						<ListItem>Google</ListItem>
						<ListItem>Facebook</ListItem>
						<ListItem>Instagram</ListItem>
						<ListItem>Twitter</ListItem>
						<ListItem>LinkedIn</ListItem>
					</List>
					<Paragraph>
						If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.
					</Paragraph>
					<Paragraph>
						You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.
					</Paragraph>
				</Section>
				
				<Section>
					<SectionTitle>Tracking Technologies and Cookies</SectionTitle>
					<Paragraph>
						We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
					</Paragraph>
					<List>
						<ListItem><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</ListItem>
						<ListItem><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</ListItem>
					</List>
				</Section>
				
				<Section>
					<SectionTitle>Use of Your Personal Data</SectionTitle>
					<Paragraph>The Company may use Personal Data for the following purposes:</Paragraph>
					<List>
						<ListItem><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</ListItem>
						<ListItem><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</ListItem>
						<ListItem><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</ListItem>
						<ListItem><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</ListItem>
						<ListItem><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</ListItem>
						<ListItem><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</ListItem>
						<ListItem><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</ListItem>
						<ListItem><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</ListItem>
					</List>
				</Section>
				
				<Section>
					<SectionTitle>Disclosure of Your Personal Data</SectionTitle>
					
					<SubSectionTitle>Business Transactions</SubSectionTitle>
					<Paragraph>
						If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
					</Paragraph>
					
					<SubSectionTitle>Law enforcement</SubSectionTitle>
					<Paragraph>
						Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
					</Paragraph>
					
					<SubSectionTitle>Other legal requirements</SubSectionTitle>
					<Paragraph>
						The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
					</Paragraph>
					<List>
						<ListItem>Comply with a legal obligation</ListItem>
						<ListItem>Protect and defend the rights or property of the Company</ListItem>
						<ListItem>Prevent or investigate possible wrongdoing in connection with the Service</ListItem>
						<ListItem>Protect the personal safety of Users of the Service or the public</ListItem>
						<ListItem>Protect against legal liability</ListItem>
					</List>
				</Section>
				
				<Section>
					<SectionTitle>Security of Your Personal Data</SectionTitle>
					<Paragraph>
						The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
					</Paragraph>
				</Section>
				
				<Section>
					<SectionTitle>Children's Privacy</SectionTitle>
					<Paragraph>
						Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
					</Paragraph>
					<Paragraph>
						If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
					</Paragraph>
				</Section>
				
				<Section>
					<SectionTitle>Links to Other Websites</SectionTitle>
					<Paragraph>
						Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
					</Paragraph>
					<Paragraph>
						We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
					</Paragraph>
				</Section>
				
				<Section>
					<SectionTitle>Changes to this Privacy Policy</SectionTitle>
					<Paragraph>
						We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
					</Paragraph>
					<Paragraph>
						We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
					</Paragraph>
					<Paragraph>
						You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
					</Paragraph>
				</Section>
				
				<Section>
					<SectionTitle>Contact Us</SectionTitle>
					<Paragraph>If you have any questions about this Privacy Policy, You can contact us:</Paragraph>
					<List>
						<ListItem>By email: contact@hirepath.com</ListItem>
					</List>
				</Section>
				
				<LastUpdated>
					This Privacy Policy was last updated on {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
				</LastUpdated>
			</Container>
			<Footer />
		</Page>
	);
};

export default PrivacyPolicy;